CREATE TABLE IF NOT EXISTS urls (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS url_checks (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	url_id INTEGER REFERENCES urls (id) NOT NULL,
	status_code INTEGER,
	h1 VARCHAR(255) NULL,
	title VARCHAR(255) NULL,
	description TEXT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);