<?php require_once(__DIR__ . '/../header.phtml') ?>

<h1>Сайт: <?= $url->getName() ?></h1>
<div class="table-responsive">
	<table class="table table-bordered table-hover text-nowrap" data-test="url">
		<tbody>
			<tr>
				<td>ID</td>
				<td><?= $url->getId() ?></td>
			</tr>
			<tr>
				<td>Имя</td>
				<td><?= $url->getName() ?></td>
			</tr>
			<tr>
				<td>Дата создания</td>
				<td><?= $url->getCreatedAt() ?></td>
			</tr>
		</tbody>
	</table>
</div>
<h2 class="mt-5 mb-3">Проверки</h2>
<form method="post" action="/urls/1/checks">
	<input type="submit" class="btn btn-primary" value="Запустить проверку">
</form>
<table class="table table-bordered table-hover" data-test="checks">
	<thead>
	<tr>
		<th>ID</th>
		<th>Код ответа</th>
		<th>h1</th>
		<th>title</th>
		<th>description</th>
		<th>Дата создания</th>
	</tr>
	</thead>
	<tbody>
	
	</tbody>
</table>

<?php require_once(__DIR__ . '/../footer.phtml') ?>
