<?php
	$navLinks = [
		'main' => ['title' => 'Главная', 'path' => $router->urlFor('main')],
		'urls' => ['title' => 'Сайты', 'path' => $router->urlFor('urls')]
	];
	$cuurenPath = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
?>
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Анализатор страниц</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
	</head>
	<body class="min-vh-100 d-flex flex-column">
		<header class="flex-shrink-0">
			<nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
				<a class="navbar-brand" href="<?= $router->urlFor('main') ?>">Анализатор страниц</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<?php foreach ($navLinks as $navLink): ?>
						<li class="nav-item">
							<a class="nav-link<?= ($navLink['path'] === $cuurenPath ? ' active' : '') ?>" href="<?= $navLink['path'] ?>"><?= $navLink['title'] ?></a>
						</li>
						<?php endforeach ?>
					</ul>
				</div>
			</nav>
		</header>
		<main class="flex-grow-1">
			<?php if (!empty($flash['result'])): ?>
				<div class="alert alert-success" role="alert">
				<?= implode("<br/>", $flash['result']) ?>
				</div>
			<?php endif; ?>
			<div class="container-lg mt-3">
			