{% extends 'template.phtml' %}
{% block body %}
<div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        <form action="{{ url_for('create_url') }}" method="post" class="row" required>
            <div class="col-8">
                <label for="text" class="visually-hidden">Url для проверки</label>
                <input type="text" name="url[name]" value="{{ url.name }}" class="form-control form-control-lg{% if flashMessages.validation is defined %} is-invalid{% endif %}" placeholder="https://www.example.com" />
                {% if flashMessages.validation is defined %}
                <div class="invalid-feedback">
                {% for message in flashMessages.validation %}
                    {{ message }}
                {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="col-2">
                <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
            </div>
        </form>
    </div>
</div>
{% endblock %}
